# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product", "0204_remove_digitalcontent_from_state"),
        ("tax", "0011_merge_20250530_0929"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="product",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="product_external_reference_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="productvariant",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="variant_external_reference_idx"
            ),
        ),
    ]
