# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0100_remove_user_user_search_gin_and_more"),
        ("channel", "0027_channel_allow_legacy_gift_card_use"),
        ("shipping", "0037_merge_20250630_1332"),
        ("warehouse", "0035_alter_warehouse_metadata_and_more"),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="warehouse",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="warehouse_external_reference_idx"
            ),
        ),
    ]
