# Generated by Django 5.2.11 on 2026-04-15 11:12

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0072_transaction_date_indexes"),
    ]
    atomic = False

    operations = [
        RemoveIndexConcurrently(
            model_name="transactionitem",
            name="app_identifier_idx",
        ),
    ]
