# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0100_remove_user_user_search_gin_and_more"),
        ("channel", "0027_channel_allow_legacy_gift_card_use"),
        ("checkout", "0093_propagate_checkout_delivery"),
        ("giftcard", "0024_alter_giftcardevent_type"),
        ("shipping", "0037_merge_20250630_1332"),
        ("warehouse", "0035_alter_warehouse_metadata_and_more"),
    ]
    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="checkout",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["authorize_status"], name="checkout_authorize_status_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="checkout",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["charge_status"], name="checkout_charge_status_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="checkoutdelivery",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_shipping_method_id"],
                name="checkout_delivery_externalid_idx",
            ),
        ),
    ]
