# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0055_assignedvariantattributevalue_variant"),
        ("page", "0035_page_page_slug_btree_idx"),
        ("product", "0204_remove_digitalcontent_from_state"),
    ]
    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name="attribute",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="attribute_external_reference_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="attributevalue",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="att_val_external_reference_idx"
            ),
        ),
    ]
