# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("discount", "0087_merge_20250630_1332"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="vouchercode",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["code"], name="vouchercode_code_idx"
            ),
        ),
    ]
