# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0100_remove_user_user_search_gin_and_more"),
        ("channel", "0027_channel_allow_legacy_gift_card_use"),
        ("discount", "0088_vouchercode_vouchercode_code_idx"),
        ("giftcard", "0025_giftcard_giftcard_code_idx"),
        ("order", "0221_remove_digital_orderevents"),
        ("shipping", "0037_merge_20250630_1332"),
        ("tax", "0011_merge_20250530_0929"),
        ("warehouse", "0035_alter_warehouse_metadata_and_more"),
    ]
    atomic = False

    operations = [
        RemoveIndexConcurrently(
            model_name="order",
            name="order_search_gin",
        ),
        RemoveIndexConcurrently(
            model_name="order",
            name="order_email_search_gin",
        ),
        AddIndexConcurrently(
            model_name="order",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["authorize_status"], name="order_authorize_status_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="order",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["charge_status"], name="order_charge_status_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="order",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="order_external_reference_idx"
            ),
        ),
    ]
