# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0099_remove_digitalcontent_customerevent_type"),
        ("permission", "0002_alter_permission_content_type"),
    ]
    atomic = False

    operations = [
        RemoveIndexConcurrently(
            model_name="user",
            name="user_search_gin",
        ),
        RemoveIndexConcurrently(
            model_name="user",
            name="user_email_idx",
        ),
        AddIndexConcurrently(
            model_name="user",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["external_reference"], name="user_external_reference_idx"
            ),
        ),
    ]
