# Generated by Django 5.2.11 on 2026-04-15 11:12

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("account", "0100_remove_user_user_search_gin_and_more"),
        ("app", "0038_merge_20260213_1154"),
        ("giftcard", "0024_alter_giftcardevent_type"),
        ("order", "0221_remove_digital_orderevents"),
        ("product", "0204_remove_digitalcontent_from_state"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="giftcard",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["code"], name="giftcard_code_idx"
            ),
        ),
    ]
